name: Build Flet APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet and dependencies
        run: |
          pip install --upgrade pip
          pip install flet
          flet --version

      - name: Check files
        run: ls -R  # Ity dia hanampy antsika hahita raha ao amin'ny toerana marina ny main.py

      - name: Build APK
        # Manampy "--force" sy ny "verbose" mba hahitana ny error marina
        run: flet build apk --name "TOJONIRINA" --project-id "com.tojonirina.app" --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TOJONIRINA-APK
          path: build/apk/app-release.apk
