name: Build Flet APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install Flet
        run: pip install flet

      - name: Build APK
        run: flet build apk --name "TOJONIRINA" --project-id "com.tojonirina.app"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TOJONIRINA-APK
          path: build/apk/app-release.apk
